import { useEffect, useMemo, useState } from "react";
import UnderstandBreadcrumbs from "../../components/understand/UnderstandBreadcrumbs";
import UnderstandContentRenderer from "../../components/understand/UnderstandContentRenderer";
import { UnderstandErrorState, UnderstandLoadingState } from "../../components/understand/UnderstandStates";
import { useTargetFocus, useUnderstandData } from "../../components/understand/useUnderstandData";
import { loadUnderstandBibliography } from "../../data/v2/understandV2";
import { understandBibliographyHash, understandModuleHash } from "../../utils/appRoute";

const SCROLL_KEY = "mosaique:understand:bibliography-scroll";

export default function UnderstandBibliographyPage({ sourceId }: { sourceId?: string }) {
  const { data, error } = useUnderstandData(loadUnderstandBibliography); const [moduleFilter, setModuleFilter] = useState(""); const [natureFilter, setNatureFilter] = useState(""); const [statusFilter, setStatusFilter] = useState(""); const selected = sourceId ? data?.find(({ id }) => id === sourceId) : undefined; const valid = !sourceId || Boolean(selected); useTargetFocus(sourceId ? `source-${sourceId}` : undefined, Boolean(data && valid));
  useEffect(() => { if (!sourceId && data) { const saved = Number(sessionStorage.getItem(SCROLL_KEY)); if (Number.isFinite(saved) && saved > 0) requestAnimationFrame(() => window.scrollTo({ top: saved, behavior: "auto" })); } }, [data, sourceId]);
  const natures = useMemo(() => [...new Set(data?.map(({ nature }) => nature) ?? [])].sort((a, b) => a.localeCompare(b, "fr")), [data]); const statuses = useMemo(() => [...new Set(data?.map(({ status }) => status) ?? [])].sort((a, b) => a.localeCompare(b, "fr")), [data]);
  if (error) return <UnderstandErrorState message="La bibliographie publique ne peut pas être chargée." />;
  if (!data) return <UnderstandLoadingState />;
  if (!valid) return <UnderstandErrorState message={`La source « ${sourceId} » n’appartient pas à la plage publique S001–S164.`} />;
  const filtered = data.filter((entry) => (!moduleFilter || entry.moduleIds.includes(moduleFilter as never)) && (!natureFilter || entry.nature === natureFilter) && (!statusFilter || entry.status === statusFilter));
  return <main className="understand-page"><div className="understand-page__inner"><UnderstandBreadcrumbs current="Bibliographie" /><header className="understand-header"><h1 id="understand-page-title" tabIndex={-1}>Bibliographie publique</h1><p>164 références, de S001 à S164.</p></header><form className="understand-filters" onSubmit={(event) => event.preventDefault()}><label>Module<select value={moduleFilter} onChange={(event) => setModuleFilter(event.target.value)}><option value="">Tous les modules</option>{Array.from({ length: 12 }, (_, index) => `M${String(index + 1).padStart(2, "0")}`).map((id) => <option key={id}>{id}</option>)}</select></label><label>Nature<select value={natureFilter} onChange={(event) => setNatureFilter(event.target.value)}><option value="">Toutes les natures</option>{natures.map((nature) => <option key={nature}>{nature}</option>)}</select></label><label>Statut<select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="">Tous les statuts</option>{statuses.map((status) => <option key={status}>{status}</option>)}</select></label><button type="button" onClick={() => { setModuleFilter(""); setNatureFilter(""); setStatusFilter(""); }}>Réinitialiser les filtres</button></form><p className="understand-result-count" aria-live="polite">{filtered.length} référence{filtered.length > 1 ? "s" : ""} affichée{filtered.length > 1 ? "s" : ""}.</p><div className="understand-bibliography">{filtered.map((entry) => <article key={entry.id} id={`source-${entry.id}`} tabIndex={-1} className="understand-source"><h2><a href={understandBibliographyHash(entry.id)} onClick={() => sessionStorage.setItem(SCROLL_KEY, String(window.scrollY))}>{entry.id}</a></h2><UnderstandContentRenderer blocks={entry.reference} /><dl className="understand-meta"><div><dt>Nature</dt><dd>{entry.nature}</dd></div><div><dt>Statut</dt><dd>{entry.status}</dd></div></dl>{entry.moduleIds.length > 0 && <p><strong>Modules associés :</strong> {entry.moduleIds.map((id, index) => <span key={id}>{index > 0 && ", "}<a href={understandModuleHash(id)}>{id}</a></span>)}</p>}{entry.links.length > 0 && <ul>{entry.links.map((link, index) => <li key={`${link.href}-${index}`}><a href={link.href}>{link.label}<span className="sr-only"> (lien externe)</span></a></li>)}</ul>}{entry.maintenance && <aside className="understand-dated"><h3>Maintenance documentaire</h3>{entry.maintenance.verifiedAt && <p>Vérifié le {entry.maintenance.verifiedAt}.</p>}{entry.maintenance.recommendedFrequency && <p>Fréquence recommandée : {entry.maintenance.recommendedFrequency}.</p>}</aside>}</article>)}</div><p><a href="#/comprendre">Retour à Comprendre</a></p></div></main>;
}
